[build-system]
requires = ["uv_build >= 0.10.10, <0.12.0"]
build-backend = "uv_build"

[project]
name = "equiformer_v3"
version = "0.0.3"
description = "Equiformer v3"
readme = "README.md"
requires-python = ">=3.11"
dynamic = []

dependencies = [
    "ase>=3.22,<4.0",
    "numpy>=1.26,<3.0",
    "myplots>=0.1.1",
    "fairchem-core",
    "torch==2.9.1",
    "scipy<1.12",
    "torchvision",
    "torchaudio",
    "torch_geometric",
    "torch-scatter==2.1.2+pt29cu126",
    "torch-sparse==0.6.18+pt29cu126",
    "torch-cluster==1.6.3+pt29cu126",
    "torch-spline-conv==1.2.2+pt29cu126",
]

[tool.uv]
find-links = ["https://data.pyg.org/whl/torch-2.9.1+cu126.html"]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"

[tool.uv.build-backend]
source-include = ["src"]
exclude = ["src/equiformer_v3/experimental"]

# UV build
[tool.uv_build]
include = ["fairchem/**/*.pyi", "fairchem/py.typed"]

[project.urls]
Repository = "https://github.com/daniisler/equiformer_v3/tree/feature-python-package"
